/*
 * Location API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API. 
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// DeleteLocation - Delete a location
func (s *DefaultApiService) DeleteLocation(locationName string) (interface{}, error) {
	// TODO - update DeleteLocation with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DeleteLocation' not implemented")
}

// FindAllLocations - Get all locations
func (s *DefaultApiService) FindAllLocations() (interface{}, error) {
	// TODO - update FindAllLocations with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'FindAllLocations' not implemented")
}

// FindLocation - Find a location
func (s *DefaultApiService) FindLocation(locationName string) (interface{}, error) {
	// TODO - update FindLocation with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'FindLocation' not implemented")
}

// InsertLocation - Insert a new location
func (s *DefaultApiService) InsertLocation(locationName string, latitude float32, longitude float32) (interface{}, error) {
	// TODO - update InsertLocation with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'InsertLocation' not implemented")
}

// UpdateLocation - Update an existing location
func (s *DefaultApiService) UpdateLocation(locationName string, description string) (interface{}, error) {
	// TODO - update UpdateLocation with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'UpdateLocation' not implemented")
}
