/**
 * Location API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LocationApi);
  }
}(this, function(expect, LocationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LocationApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('deleteLocation', function() {
      it('should call deleteLocation successfully', function(done) {
        //uncomment below and update the code to test deleteLocation
        //instance.deleteLocation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findAllLocations', function() {
      it('should call findAllLocations successfully', function(done) {
        //uncomment below and update the code to test findAllLocations
        //instance.findAllLocations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findLocation', function() {
      it('should call findLocation successfully', function(done) {
        //uncomment below and update the code to test findLocation
        //instance.findLocation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('insertLocation', function() {
      it('should call insertLocation successfully', function(done) {
        //uncomment below and update the code to test insertLocation
        //instance.insertLocation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateLocation', function() {
      it('should call updateLocation successfully', function(done) {
        //uncomment below and update the code to test updateLocation
        //instance.updateLocation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
