/*
 * Location API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"
	"strconv"
	"strings"

	"github.com/gorilla/mux"
)

// A DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer) Router {
	databaseConnect()
	return &DefaultApiController{ service: s }
}

// Routes returns all of the api route for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{ 
		{
			"DeleteLocation",
			strings.ToUpper("Delete"),
			"/LocationAPI/location/{locationName}",
			c.DeleteLocation,
		},
		{
			"FindAllLocations",
			strings.ToUpper("Get"),
			"/LocationAPI/locations",
			c.FindAllLocations,
		},
		{
			"FindLocation",
			strings.ToUpper("Get"),
			"/LocationAPI/location/{locationName}",
			c.FindLocation,
		},
		{
			"InsertLocation",
			strings.ToUpper("Post"),
			"/LocationAPI/location/{locationName}",
			c.InsertLocation,
		},
		{
			"UpdateLocation",
			strings.ToUpper("Put"),
			"/LocationAPI/location/{locationName}",
			c.UpdateLocation,
		},
	}
}

// DeleteLocation - Delete a location
func (c *DefaultApiController) DeleteLocation(w http.ResponseWriter, r *http.Request) {
	fmt.Println("DeleteLocation")
	params := mux.Vars(r)
	locationName := params["locationName"]
	result, err := c.service.DeleteLocation(locationName)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// FindAllLocations - Get all locations
func (c *DefaultApiController) FindAllLocations(w http.ResponseWriter, r *http.Request) {
	fmt.Println("FindAllLocation")
	result, err := c.service.FindAllLocations()
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// FindLocation - Find a location
func (c *DefaultApiController) FindLocation(w http.ResponseWriter, r *http.Request) {
	fmt.Println("FindLocation")
	params := mux.Vars(r)
	locationName := params["locationName"]
	result, err := c.service.FindLocation(locationName)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// InsertLocation - Insert a new location
func (c *DefaultApiController) InsertLocation(w http.ResponseWriter, r *http.Request) {
	fmt.Println("InsertLocation")

	params := mux.Vars(r)
	query := r.URL.Query()
	locationName := params["locationName"]
	valueLat, errLat := strconv.ParseFloat(query.Get("latitude"), 32)
	valueLon, errLon := strconv.ParseFloat(query.Get("longitude"), 32)
	description := query.Get("description")

	if errLat != nil || errLon != nil {
		//Could not convert lat or lon strings to float
		w.WriteHeader(400)
	}
	latitude := float32(valueLat)
	longitude := float32(valueLon)

	result, err := c.service.InsertLocation(locationName, latitude, longitude, description)

	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// UpdateLocation - Update an existing location
func (c *DefaultApiController) UpdateLocation(w http.ResponseWriter, r *http.Request) {
	fmt.Println("UpdatedLocation")
	params := mux.Vars(r)
	query := r.URL.Query()
	locationName := params["locationName"]
	description := query.Get("description")
	result, err := c.service.UpdateLocation(locationName, description)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}
