name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Get pgx
      run: go get github.com/jackc/pgx/v4
      
    - name: Get pgx connection pool
      run: go get github.com/jackc/pgx/v4/pgxpool

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
